#################################################################
# +-----------------------------------------------------------+ #
# |                 PvChat Server config file                 | #
# +-----------------------------------------------------------+ #
#################################################################

# more information on https://github.com/janu8ry/pvchat



port:
  32198

enable-log:
  true

password:
  none